# Generated by Django 3.0.8 on 2020-07-19 07:09

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'}),
        ),
    ]
