# Generated by Django 3.0.8 on 2020-07-19 11:21

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_resident_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident_profile',
            name='home_location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'}),
        ),
    ]
