# Generated by Django 3.0.8 on 2020-07-19 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0004_auto_20200719_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('facility_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('police', 'Police Post'), ('hospital', 'Hospital/Healthcare center')], default='police', max_length=50)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.Neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=150)),
                ('business_email', models.EmailField(max_length=254)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.82, -1.29], 'marker_color': 'blue'})),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.Neighbourhood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
