# Generated by Django 3.0.8 on 2020-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_business_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
